Fixes #2281: Make MockedConstruction stubs close on demand
mockito/mockito pull request #2442
Opened 2021-10-05 20:29 UTC by temp-droid

MockedConstruction should behave like MockedStatic when we use @Mock on it.

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

Allows this kind of test to work in multiple test files:
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.MockedConstruction;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(MockitoExtension.class)
public class Test1 {

    @Test
    void testStatic(@Mock MockedStatic<ClassToMock> mockedStatic) {
        assertNotNull(mockedStatic);
    }

    @Test
    void testMockedConstruction(@Mock MockedConstruction<ClassToMock> mockConstruction) {
//        mockConstruction.closeOnDemand();
        assertNotNull(mockConstruction);
    }
}
```
Otherwise the `mockConstruction` object won't be closed and generate error described in #2281.

2021-10-05 20:45 UTC, TimvdLippe requested changes
Please add the regression test that you mentioned in your PR description to our test suite in https://github.com/mockito/mockito/tree/main/subprojects/junit-jupiter/src/test/java/org/mockitousage

2021-10-06 06:57 UTC, temp-droid commented
Hi @TimvdLippe , tests have been added. Feel free to mention if something needs to be changed!

Sorry if I messed up with the merge (not sure why it was needed), I hope we can squash everything before merging to hide it?

2021-10-06 12:22 UTC, raphw approved these changes
Obvious oversight. Good to merge.

2021-10-06 14:59 UTC, TimvdLippe requested changes
Change looks good to me. We can clean up the commit message when we squash-merge, so don't worry about that 😄 

Only a small nit with regard to the missing license. Other than that this is ready to go.

2021-10-06 14:59 UTC, TimvdLippe commented on subprojects/junit-jupiter/src/test/java/org/mockitousage/CloseOnDemandTest.java
> +package org.mockitousage;
This file is missing a license header:

```
/*
 * Copyright (c) 2021 Mockito contributors
 * This program is made available under the terms of the MIT License.
 */
```

You can run `./gradlew build` locally to get it passing. (You might also need to run `./gradlew spotlessApply` to make the formatter happy)

2021-10-06 18:54 UTC, TimvdLippe approved these changes
Thanks for the fix!

2021-10-06 18:54 UTC, merged