Fixes #2548 : Makes InOrder able to verify static methods
mockito/mockito pull request #2549
Opened 2022-01-24 21:02 UTC by mirkoalicastro

## Checklist

 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [ ] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

2022-02-15 16:41 UTC, TimvdLippe requested changes
Thanks for the PR! Overall, the implementation looks solid. I only have a couple of nits with regards to the tests.

My only concern is the difference in the class passed into `inOrder` and the class we are actually interacting with. I guess this currently works, as we are passing in a `Class` in the `List<Object>`, but that feels a bit weird to me. Not sure WDYT?

I think to fix that, we would need a similar method to `objectIsMockToBeVerified`, but in this case verify that the context is correct. However, we are only passing in the lambda, which doesn't necessarily match to the `Class` we put in.

Therefore, we maybe have to look into passing the `mockedStatic` in the `inOrder` method instead and omit it as an argument from the `inOrder.verify` call?

2022-02-15 16:41 UTC, TimvdLippe commented on subprojects/inline/src/test/java/org/mockitoinline/InOrderVerificationTest.java
> +    @Test(expected = VerificationInOrderFailure.class)
Nit: do not use `@Test(expected)` and instead use `org.assertj.core.api.Assertions.assertThatThrownBy`. We recently migrated away from that in #2510 (I should probably check if we can enable ErrorProne to error on this).

2022-02-16 17:07 UTC, mirkoalicastro commented on subprojects/inline/src/test/java/org/mockitoinline/InOrderVerificationTest.java
> +public class InOrderVerificationTest {
Definitely, it looks a great test to add. Done!

2022-02-16 17:09 UTC, mirkoalicastro commented on subprojects/inline/src/test/java/org/mockitoinline/InOrderVerificationTest.java
> +    private void mockedStaticTest(Consumer<MockedStatic<StaticContext>> body) {
Sure, I see your point. I have inlined that in the tests.

2022-02-16 17:36 UTC, mirkoalicastro commented
> Thanks for the PR! Overall, the implementation looks solid. I only have a couple of nits with regards to the tests.
> 
> My only concern is the difference in the class passed into `inOrder` and the class we are actually interacting with. I guess this currently works, as we are passing in a `Class` in the `List<Object>`, but that feels a bit weird to me. Not sure WDYT?
> 
> I think to fix that, we would need a similar method to `objectIsMockToBeVerified`, but in this case verify that the context is correct. However, we are only passing in the lambda, which doesn't necessarily match to the `Class` we put in.
> 
> Therefore, we maybe have to look into passing the `mockedStatic` in the `inOrder` method instead and omit it as an argument from the `inOrder.verify` call?

Thanks for your feedback @TimvdLippe ! I have addressed the comments and pushed the changes related to the tests.

I see your concern, and actually, passing the `mockedStatic` to the `inOrder` method was my initial idea. Here is the reason why I moved away from that.
Let's assume we have two static mocks (two different classes), and we want to verify them in order. Then, we'd pass two `MockedStatic` instances to the `inOrder` method.
When it comes to the verification, we'd have `InOrder#verify(Verification)`, where `Verification` is a lambda (no parameters, void return type) because `MockedStatic#verify` deals with a lambda. Given a lambda, we can't assert if it contains a static method reference, or contains just some statements. That is, we can't retrieve the `Class` instance. Without this, we can't select and use the appropriate `MockedStatic` instance to verify the lambda.
Moreover, the above assumes we have the `Class` instance of the `MockedStatic` somehow available in `InOrderImpl`, but currently, that is not the case. Of course, we could add a method to `MockedStatic` that accepts a `Class` and returns true if the `Class` is the same as what is mocking (package private maybe?). 
I see your concern, but I think we have the same situation in the `MockedStatic#verify` methods, where we could pass things not relevant to the context. But I can't see a different way to solve it otherwise, if possible.
WDYT?

2022-02-16 21:32 UTC, TimvdLippe approved these changes
Awesome, thanks for the explanation (makes sense to me) and the nice PR + tests! Merging 🎉

2022-02-16 21:32 UTC, merged