Bump versions.errorprone from 2.11.0 to 2.12.0
mockito/mockito pull request #2608
Opened 2022-04-05 11:45 UTC by rickie

Fixes #2554. 

Today ErrorProne [2.12.0](https://github.com/google/error-prone/releases/tag/v2.12.0) has been released. It contains https://github.com/google/error-prone/issues/2926, which fixes the incompatibility issue for Mockito. 
We are blocked internally on the new Mockito release and therefore decided to help out and open this PR.

I'm open to other ideas on how to improve the code.  

---
Bumps `versions.errorprone` from 2.11.0 to 2.12.0.

Updates `error_prone_core` from 2.11.0 to 2.12.0
- [Release notes](https://github.com/google/error-prone/releases)
- [Commits](https://github.com/google/error-prone/compare/v2.11.0...v2.12.0)

Updates `error_prone_test_helpers` from 2.11.0 to 2.12.0
- [Release notes](https://github.com/google/error-prone/releases)
- [Commits](https://github.com/google/error-prone/compare/v2.11.0...v2.12.0)

---
updated-dependencies:
- dependency-name: com.google.errorprone:error_prone_core
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.google.errorprone:error_prone_test_helpers
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

2022-04-05 15:08 UTC, TimvdLippe requested changes
This LGTM, but can you please update the base branch to `main` so that I can cleanly merge this PR? Then we can close #2553 as well.

2022-04-06 06:55 UTC, TimvdLippe approved these changes
Thanks for the fixes!

2022-04-06 06:55 UTC, merged

2022-04-17 10:44 UTC, Stephan202 commented
@TimvdLippe would it be possible to get a Maven Central release with these changes? As-is we're blocked from upgrading Error Prone (unless we disable `mockito-errorprone`, of course).

2022-04-17 13:34 UTC, TimvdLippe commented
@Stephan202 We are working on #2613 and will publish a new minor release including that PR.

2022-04-19 18:52 UTC, TimvdLippe commented
4.5.0 is now available on Maven Central: https://repo1.maven.org/maven2/org/mockito/mockito-core/4.5.0/